Mox.defmock(DokkuRadar.DockerClient.Mock, for: DokkuRadar.DockerClient)
Mox.defmock(DokkuRadar.FilesystemReader.Mock, for: DokkuRadar.FilesystemReader)
Mox.defmock(DokkuRadar.Service.Mock, for: DokkuRadar.Service)
Mox.defmock(DokkuRadar.ServicePlugin.Mock, for: DokkuRadar.ServicePlugin)
Mox.defmock(DokkuRadar.ServicePlugins.Mock, for: DokkuRadar.ServicePlugins)
Mox.defmock(DokkuRadar.ServiceCache.Mock, for: DokkuRadar.ServiceCache)
Mox.defmock(DokkuRadar.Collector.Mock, for: DokkuRadar.Collector)
